# render.yaml
services:
  - type: web
    name: egg-ai-assistant
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOSE_API_ENDPOINT
        sync: false
    autoDeploy: true
    healthCheckPath: /
    buildFilter:
      paths:
        - package.json
        - server.js
        - index.html
        - styles.css
        - script.js
        - src/**